### ISSUE TITLE
Diseño Wireframe

### ISSUE THREAD

**Issue by ecortescl** [ecortescl/platform-booking-frontend#18]
Deben elaborar el wireframe de la aplicación consideran todo los elementos necesarios nombrados en las issue tienen que usar de referencia

[www.agendapro.cl](https://agendapro.com/cl)
[www.calendly.cl](https://calendly.com/)

Tambien no es necesario que inventen todo denuevo pueden utilizar Admin Vue Opensource o si encuentran uno en envato yo se lo puedo descargar

https://elements.envato.com/es/web-templates/vue

Gratuitos
https://admin.vuestic.dev/
https://coreui.io/vue/

No es necesario que usen estos elementos incluso pueden solo servir de inspiración

Recuerden crearse una cuenta en [m](https://miro.com/)  para diseñar el wireframe dejo un curso para su uso

https://www.youtube.com/watch?v=BRuNwXAGEG8
https://www.youtube.com/watch?v=4Azc4Gs2nlU

**Comment by vicentejavierc** [comment]
https://miro.com/app/board/uXjVLXYETuc=/?userEmail=vicentecollado11%40gmail.com&track=true&utm_source=notification&utm_medium=email&utm_campaign=add-to-team-and-board&utm_content=go-to-board
